// Vercel Function: AI Interviewer brain.
//
// The /templates/interview demo page drives a real Agent Room (room_create
// + candidate-web join + "AI Interviewer" cc-participant join) entirely
// browser-side. This function is the thin LLM call that decides what
// the Interviewer says next — given the running transcript, return the
// next line. The page handles posting the reply to the room.
//
// Two modes:
//   1. ANTHROPIC_API_KEY in env → real Claude call, full conversational AI.
//   2. No key → scripted ladder of interview questions. Still posts real
//      messages to a real room, so the demo "AI is in the room" property
//      holds even before Robin wires the LLM key in Vercel.
//
// Stays minimal on purpose: no workspace imports (this file ships in
// the Vercel function bundle as plain Node, see api/report-page.ts
// hotfix #29 for the rationale), no DB writes, no external state.

import type { VercelRequest, VercelResponse } from '@vercel/node';

interface InboundMessage {
  speaker: 'candidate' | 'interviewer';
  text: string;
}

interface ReplyRequest {
  /** Room code — we don't actually fetch from Upstash here, but the page
   *  passes it so server logs can correlate with a specific session. */
  code?: string;
  /** Transcript so far, oldest first. The candidate's most recent line
   *  is the trigger for our reply. */
  transcript?: InboundMessage[];
  /** Optional: stage hint from the page (e.g. "wrap" → "ask for any
   *  questions and end the interview"). The page uses this to bound the
   *  session length without baking it into the prompt. */
  stage?: 'opening' | 'depth' | 'tradeoffs' | 'behavioral' | 'wrap';
}

interface ReplyResponse {
  text: string;
  /** True if this reply was generated by the live LLM; false if the
   *  scripted ladder fallback fired. The page surfaces this on the
   *  Interviewer's message bubble so we don't pretend the demo is
   *  smarter than it is when the key isn't set. */
  ai: boolean;
  /** Echoes the stage we used so the page can advance its own state. */
  stage: ReplyRequest['stage'];
}

const SCRIPTED_LADDER: Record<NonNullable<ReplyRequest['stage']>, string[]> = {
  opening: [
    "Hi — thanks for taking the time. I'll keep this to about 20 minutes. To start: walk me through the project from your last 6 months you're proudest of. What was the thing you owned, what was the trade-off you optimized for, and what would you do differently?",
  ],
  depth: [
    "That's a useful framing. Going one level deeper: what specifically did you give up to get the upside you described? I'm asking because the candidates I worry about are the ones who can't name what they traded away.",
    "Got it. One follow-up — at what point did you realize the original plan wasn't going to work, and what tipped it for you? I'm trying to read your debugging instincts.",
  ],
  tradeoffs: [
    "Switching gears for a minute. Imagine you have a service that's hitting 99.5% uptime but the team is exhausted from on-call. The CEO wants 99.9%. How do you push back, and what data would you bring?",
    "If you had to pick one of: cleaner architecture, faster shipping, or fewer outages — for the next quarter only — which do you pick and why? No 'all three' allowed.",
  ],
  behavioral: [
    "Tell me about a time you disagreed with a more senior person on a technical call. Walk me through what they were arguing, what you were arguing, and how it actually resolved. Names off, specifics on.",
    "Last one in this round — when did you most recently change your mind about something you'd previously been confident in? What changed?",
  ],
  wrap: [
    "Good answers across the board. Two minutes left — anything you want me to flag to the hiring manager that we didn't cover? Could be a strength I missed or a concern you'd rather raise yourself.",
    "Thanks, Priya — wrapping up. You'll get a structured scorecard out of this session within an hour, and the hiring manager will follow up directly. Have a good rest of your day.",
  ],
};

function pickScriptedLine(stage: NonNullable<ReplyRequest['stage']>, turnsAtStage: number): string {
  const lines = SCRIPTED_LADDER[stage];
  return lines[Math.min(turnsAtStage, lines.length - 1)] ?? lines[0]!;
}

function approxTurnsAtStage(transcript: InboundMessage[], stage: NonNullable<ReplyRequest['stage']>): number {
  // Rough heuristic: count how many interviewer lines we've already
  // produced. Used only by the scripted fallback to pick the next
  // line in the ladder without storing per-session state.
  void stage;
  return transcript.filter(m => m.speaker === 'interviewer').length;
}

const SYSTEM_PROMPT = `You are an AI interviewer running a 20-minute first-round screen for a software engineering role at an SMB SaaS company. You stay neutral, ask one question at a time, and probe for trade-off awareness, debugging instincts, and self-awareness about what didn't go well.

Style rules:
- Each turn is one focused question or follow-up. No prefaces, no "great answer!", no over-warmth.
- When the candidate gives a vague answer, push for specifics — "what did you give up", "who pushed back", "what tipped it".
- Stay under 60 words per turn unless the question genuinely needs setup.
- Never invent rapport ("nice to meet you" is fine; "I love your background!" is not).
- End the interview cleanly when the page says stage=wrap; thank the candidate, mention the scorecard will follow.
- You will NOT see the candidate's resume — you only have the live transcript. Ask questions that work without prior context.`;

async function callAnthropic(
  apiKey: string,
  transcript: InboundMessage[],
  stage: NonNullable<ReplyRequest['stage']>
): Promise<string | null> {
  // Cheapest reliable Anthropic model for short turns. Falling back to
  // null on any error — caller flips to scripted ladder.
  const messages = transcript.map(m => ({
    role: m.speaker === 'candidate' ? 'user' : 'assistant',
    content: m.text,
  }));
  // Stage hint becomes a final user-side nudge so the model behaves
  // differently late in the interview without us baking stage into the
  // system prompt.
  if (stage === 'wrap') {
    messages.push({ role: 'user', content: '[stage: wrap — close out the interview cleanly in 1-2 turns.]' });
  } else if (stage === 'opening' && transcript.length === 0) {
    messages.push({ role: 'user', content: '[stage: opening — open the interview.]' });
  }

  let resp: Response;
  try {
    resp = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'content-type': 'application/json',
        'x-api-key': apiKey,
        'anthropic-version': '2023-06-01',
      },
      body: JSON.stringify({
        model: 'claude-haiku-4-5',
        max_tokens: 400,
        system: SYSTEM_PROMPT,
        messages: messages.length > 0 ? messages : [{ role: 'user', content: '[stage: opening — open the interview.]' }],
      }),
    });
  } catch {
    return null;
  }
  if (!resp.ok) return null;
  let body: unknown;
  try { body = await resp.json(); } catch { return null; }
  const out = (body as { content?: { type: string; text: string }[] }).content;
  if (!Array.isArray(out)) return null;
  const text = out.filter(c => c?.type === 'text').map(c => c.text).join('').trim();
  return text || null;
}

export default async function handler(req: VercelRequest, res: VercelResponse): Promise<void> {
  if (req.method !== 'POST') {
    res.status(405).json({ error: 'method_not_allowed', message: 'Use POST.' });
    return;
  }

  let parsed: ReplyRequest;
  try {
    parsed = (typeof req.body === 'string' ? JSON.parse(req.body) : req.body ?? {}) as ReplyRequest;
  } catch {
    res.status(400).json({ error: 'bad_json' });
    return;
  }

  const transcript = Array.isArray(parsed.transcript) ? parsed.transcript : [];
  const stage = parsed.stage ?? (transcript.length === 0 ? 'opening' : 'depth');

  // Try the LLM first.
  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (apiKey) {
    const text = await callAnthropic(apiKey, transcript, stage);
    if (text) {
      res.setHeader('Cache-Control', 'no-store');
      const reply: ReplyResponse = { text, ai: true, stage };
      res.status(200).json(reply);
      return;
    }
  }

  // Fallback: scripted ladder. Still real messages in a real room — just
  // not generative. The page surfaces `ai: false` so demo viewers know
  // this is the pre-LLM-key state.
  const text = pickScriptedLine(stage, approxTurnsAtStage(transcript, stage));
  res.setHeader('Cache-Control', 'no-store');
  const reply: ReplyResponse = { text, ai: false, stage };
  res.status(200).json(reply);
}
